org.apache.wss4j.crypto.merlin.keystore.type=jks
org.apache.wss4j.crypto.merlin.keystore.password=
org.apache.wss4j.crypto.merlin.keystore.alias=myservicekey
org.apache.wss4j.crypto.merlin.keystore.file=./etc/keystores/servicestore.jks
